export const IMAGES = {
    LEFT_ARROW: require('../images/leftArrow.png'),
    PENDING: require('../images/pending.png'),
    EXPORT_EXCEL: require('../images/exportExcel.png'),
    BLACK_LIST: require('../images/blackList.png'),
    BLUE_LIST: require('../images/blueList.png'),
    ADD_WORKER_BLACK: require('../images/addWorkerBlack.png'),
    ADD_WORKER_BLUE: require('../images/addWorkerBlue.png'),
    EMPTY: require('../images/empty.png'),
    FILTER: require('../images/filter.png'),
    BLACK_ADD_BUTTON: require('../images/blackAddButton.png'),
    BLUE_ADD_BUTTON: require('../images/blueAddButton.png'),
    CHECK_MARK: require('../images/checkMark.png'),
    RIGHT_ARROW: require('../images/rightArrow.png'),
    BLUE_DASHBOARD: require('../images/blueDashBoard.png'),
    BLACK_DASHBOARD: require('../images/blackDashBoard.png'),
}